using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using System.Xml.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace ProTranslate.SourceGenerator;

/// <summary>
/// Generates strongly typed key catalogs from ProTranslate AdditionalFiles.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ProTranslateKeysGenerator : IIncrementalGenerator
{
    private static readonly DiagnosticDescriptor InvalidJsonDescriptor = new(
        "PTSG001",
        "Invalid ProTranslate JSON catalog",
        "Could not parse ProTranslate JSON catalog '{0}': {1}",
        "ProTranslate.SourceGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor DuplicateKeyDescriptor = new(
        "PTSG002",
        "Duplicate ProTranslate key",
        "Translation key '{0}' is declared more than once in '{1}'",
        "ProTranslate.SourceGenerator",
        DiagnosticSeverity.Warning,
        isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<CatalogFile> catalogFiles = context.AdditionalTextsProvider
            .Where(static file => IsCatalogFile(file.Path))
            .Select(static (file, cancellationToken) => ParseCatalogFile(file, cancellationToken));

        IncrementalValueProvider<CatalogModel> catalog = catalogFiles
            .Collect()
            .Select(static (files, _) => CreateCatalogModel(files));

        context.RegisterSourceOutput(catalog, static (sourceContext, model) =>
        {
            foreach (Diagnostic diagnostic in model.Diagnostics)
            {
                sourceContext.ReportDiagnostic(diagnostic);
            }

            if (model.Keys.IsDefaultOrEmpty)
            {
                return;
            }

            sourceContext.AddSource("ProTranslateKeys.g.cs", SourceText.From(Render(model.Keys), Encoding.UTF8));
            sourceContext.AddSource("ProTranslateStrings.g.cs", SourceText.From(RenderStrings(model.Keys), Encoding.UTF8));
            sourceContext.AddSource("ProTranslateProviderManifest.g.cs", SourceText.From(RenderManifest(model), Encoding.UTF8));
            sourceContext.AddSource("ProTranslateGeneratedTranslationProvider.g.cs", SourceText.From(RenderGeneratedProvider(model), Encoding.UTF8));
        });
    }

    private static string Render(ImmutableArray<string> keys)
    {
        ImmutableArray<KeyIdentifier> identifiers = CreateIdentifiers(keys);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace ProTranslate.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static partial class ProTranslateKeys");
        builder.AppendLine("{");

        foreach (KeyIdentifier identifier in identifiers)
        {
            builder.Append("    public const string ");
            builder.Append(identifier.Name);
            builder.Append(" = ");
            builder.Append(FormatStringLiteral(identifier.Key));
            builder.AppendLine(";");
        }

        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public static partial class ProTranslateAccessors");
        builder.AppendLine("{");

        foreach (KeyIdentifier identifier in identifiers)
        {
            builder.Append("    public static ProTranslate.LocalizedString ");
            builder.Append("Get_");
            builder.Append(identifier.Name);
            builder.AppendLine("(this ProTranslate.ITranslationService translations) =>");
            builder.Append("        translations.GetString(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(");");
            builder.AppendLine();

            builder.Append("    public static string ");
            builder.Append("Value_");
            builder.Append(identifier.Name);
            builder.AppendLine("(this ProTranslate.ITranslationService translations) =>");
            builder.Append("        translations.GetString(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(").Value;");
            builder.AppendLine();

            builder.Append("    public static string Format");
            builder.Append("_");
            builder.Append(identifier.Name);
            builder.AppendLine("(this ProTranslate.ITranslationService translations, params object?[] arguments) =>");
            builder.Append("        translations.Format(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(", arguments);");
            builder.AppendLine();

            builder.Append("    public static ProTranslate.IObservableLocalizedString Observe");
            builder.Append("_");
            builder.Append(identifier.Name);
            builder.AppendLine("(this ProTranslate.ITranslationService translations, params object?[] arguments) =>");
            builder.Append("        translations.Observe(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(", arguments);");
            builder.AppendLine();
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderStrings(ImmutableArray<string> keys)
    {
        ImmutableArray<KeyIdentifier> identifiers = CreateIdentifiers(keys);
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace ProTranslate.Generated;");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class ProTranslateStrings : global::System.ComponentModel.INotifyPropertyChanged, global::System.IDisposable");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly global::ProTranslate.ITranslationService _translations;");
        builder.AppendLine("    private bool _disposed;");
        builder.AppendLine();
        builder.AppendLine("    public ProTranslateStrings(global::ProTranslate.ITranslationService translations)");
        builder.AppendLine("    {");
        builder.AppendLine("        _translations = translations ?? throw new global::System.ArgumentNullException(nameof(translations));");
        builder.AppendLine("        _translations.CultureChanged += OnCultureChanged;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public event global::System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;");
        builder.AppendLine();
        builder.AppendLine("    public global::ProTranslate.ITranslationService Translations => _translations;");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Globalization.CultureInfo Culture => _translations.CurrentCulture;");
        builder.AppendLine();
        builder.AppendLine("    public global::System.Globalization.CultureInfo UICulture => _translations.CurrentUICulture;");
        builder.AppendLine();

        foreach (KeyIdentifier identifier in identifiers)
        {
            builder.Append("    public string ");
            builder.Append(identifier.Name);
            builder.Append(" => _translations.GetString(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(").Value;");
            builder.AppendLine();

            builder.Append("    public global::ProTranslate.LocalizedString Get_");
            builder.Append(identifier.Name);
            builder.Append("() => _translations.GetString(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(");");
            builder.AppendLine();

            builder.Append("    public string Format_");
            builder.Append(identifier.Name);
            builder.Append("(params object?[] arguments) => _translations.Format(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(", arguments);");
            builder.AppendLine();

            builder.Append("    public global::ProTranslate.IObservableLocalizedString Observe_");
            builder.Append(identifier.Name);
            builder.Append("(params object?[] arguments) => _translations.Observe(ProTranslateKeys.");
            builder.Append(identifier.Name);
            builder.AppendLine(", arguments);");
            builder.AppendLine();
        }

        builder.AppendLine("    public void Refresh()");
        builder.AppendLine("    {");
        builder.AppendLine("        OnPropertyChanged(nameof(Culture));");
        builder.AppendLine("        OnPropertyChanged(nameof(UICulture));");

        foreach (KeyIdentifier identifier in identifiers)
        {
            builder.Append("        OnPropertyChanged(nameof(");
            builder.Append(identifier.Name);
            builder.AppendLine("));");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public void Dispose()");
        builder.AppendLine("    {");
        builder.AppendLine("        if (_disposed)");
        builder.AppendLine("        {");
        builder.AppendLine("            return;");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        _translations.CultureChanged -= OnCultureChanged;");
        builder.AppendLine("        _disposed = true;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    private void OnCultureChanged(object? sender, global::ProTranslate.CultureChangedEventArgs e) => Refresh();");
        builder.AppendLine();
        builder.AppendLine("    private void OnPropertyChanged(string propertyName) =>");
        builder.AppendLine("        PropertyChanged?.Invoke(this, new global::System.ComponentModel.PropertyChangedEventArgs(propertyName));");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderManifest(CatalogModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace ProTranslate.Generated;");
        builder.AppendLine();
        builder.AppendLine("public static partial class ProTranslateProviderManifest");
        builder.AppendLine("{");
        AppendManifestEntries(builder, model.ManifestEntries);
        builder.AppendLine();
        AppendStringArray(builder, "s_keys", model.Keys);
        builder.AppendLine();
        AppendStringArray(builder, "s_cultures", model.Cultures);
        builder.AppendLine();
        AppendStringArray(builder, "s_sourceFiles", model.SourceFiles);
        builder.AppendLine();
        builder.AppendLine("    public static global::System.ReadOnlySpan<ProTranslateProviderManifestEntry> Entries => s_entries;");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.ReadOnlySpan<string> Keys => s_keys;");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.ReadOnlySpan<string> Cultures => s_cultures;");
        builder.AppendLine();
        builder.AppendLine("    public static global::System.ReadOnlySpan<string> SourceFiles => s_sourceFiles;");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public readonly partial struct ProTranslateProviderManifestEntry");
        builder.AppendLine("{");
        builder.AppendLine("    private readonly int[]? _placeholderIndexes;");
        builder.AppendLine();
        builder.AppendLine("    public ProTranslateProviderManifestEntry(string key, string? culture, string sourceFile, int[] placeholderIndexes)");
        builder.AppendLine("    {");
        builder.AppendLine("        Key = key;");
        builder.AppendLine("        Culture = culture;");
        builder.AppendLine("        SourceFile = sourceFile;");
        builder.AppendLine("        _placeholderIndexes = placeholderIndexes;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public string Key { get; }");
        builder.AppendLine();
        builder.AppendLine("    public string? Culture { get; }");
        builder.AppendLine();
        builder.AppendLine("    public string SourceFile { get; }");
        builder.AppendLine();
        builder.AppendLine("    public global::System.ReadOnlySpan<int> PlaceholderIndexes => _placeholderIndexes ?? global::System.Array.Empty<int>();");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static string RenderGeneratedProvider(CatalogModel model)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("namespace ProTranslate.Generated;");
        builder.AppendLine();
        builder.AppendLine("public sealed partial class ProTranslateGeneratedTranslationProvider : global::ProTranslate.ITranslationProvider");
        builder.AppendLine("{");
        AppendProviderEntries(builder, model.ProviderEntries);
        builder.AppendLine();
        builder.AppendLine("    public ProTranslateGeneratedTranslationProvider()");
        builder.AppendLine("        : this(\"ProTranslateGenerated\")");
        builder.AppendLine("    {");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public ProTranslateGeneratedTranslationProvider(string name)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (string.IsNullOrWhiteSpace(name))");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentException(\"Provider name cannot be empty.\", nameof(name));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        Name = name;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public string Name { get; }");
        builder.AppendLine();
        builder.AppendLine("    public global::ProTranslate.LocalizedString GetString(string key, global::System.Globalization.CultureInfo culture)");
        builder.AppendLine("    {");
        builder.AppendLine("        if (string.IsNullOrWhiteSpace(key))");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentException(\"Translation key cannot be empty.\", nameof(key));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        if (culture is null)");
        builder.AppendLine("        {");
        builder.AppendLine("            throw new global::System.ArgumentNullException(nameof(culture));");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        string cultureName = culture.Name;");
        builder.AppendLine("        for (int i = 0; i < s_entries.Length; i++)");
        builder.AppendLine("        {");
        builder.AppendLine("            ProTranslateGeneratedTranslationEntry entry = s_entries[i];");
        builder.AppendLine("            if (entry.Culture is not null");
        builder.AppendLine("                && string.Equals(entry.Key, key, global::System.StringComparison.Ordinal)");
        builder.AppendLine("                && string.Equals(entry.Culture, cultureName, global::System.StringComparison.OrdinalIgnoreCase))");
        builder.AppendLine("            {");
        builder.AppendLine("                return new global::ProTranslate.LocalizedString(key, entry.Value, culture, false, Name);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        for (int i = 0; i < s_entries.Length; i++)");
        builder.AppendLine("        {");
        builder.AppendLine("            ProTranslateGeneratedTranslationEntry entry = s_entries[i];");
        builder.AppendLine("            if (entry.Culture is null");
        builder.AppendLine("                && string.Equals(entry.Key, key, global::System.StringComparison.Ordinal))");
        builder.AppendLine("            {");
        builder.AppendLine("                return new global::ProTranslate.LocalizedString(key, entry.Value, culture, false, Name);");
        builder.AppendLine("            }");
        builder.AppendLine("        }");
        builder.AppendLine();
        builder.AppendLine("        return new global::ProTranslate.LocalizedString(key, key, culture, true, Name);");
        builder.AppendLine("    }");
        builder.AppendLine("}");
        builder.AppendLine();
        builder.AppendLine("public readonly partial struct ProTranslateGeneratedTranslationEntry");
        builder.AppendLine("{");
        builder.AppendLine("    public ProTranslateGeneratedTranslationEntry(string key, string? culture, string value)");
        builder.AppendLine("    {");
        builder.AppendLine("        Key = key;");
        builder.AppendLine("        Culture = culture;");
        builder.AppendLine("        Value = value;");
        builder.AppendLine("    }");
        builder.AppendLine();
        builder.AppendLine("    public string Key { get; }");
        builder.AppendLine();
        builder.AppendLine("    public string? Culture { get; }");
        builder.AppendLine();
        builder.AppendLine("    public string Value { get; }");
        builder.AppendLine("}");
        return builder.ToString();
    }

    private static void AppendManifestEntries(StringBuilder builder, ImmutableArray<ManifestEntry> entries)
    {
        builder.AppendLine("    private static readonly ProTranslateProviderManifestEntry[] s_entries = new ProTranslateProviderManifestEntry[]");
        builder.AppendLine("    {");

        foreach (ManifestEntry entry in entries)
        {
            builder.Append("        new ProTranslateProviderManifestEntry(");
            builder.Append(FormatStringLiteral(entry.Key));
            builder.Append(", ");
            builder.Append(entry.Culture is null ? "null" : FormatStringLiteral(entry.Culture));
            builder.Append(", ");
            builder.Append(FormatStringLiteral(entry.SourceFile));
            builder.Append(", ");
            AppendIntArray(builder, entry.PlaceholderIndexes);
            builder.AppendLine("),");
        }

        builder.AppendLine("    };");
    }

    private static void AppendProviderEntries(StringBuilder builder, ImmutableArray<ProviderEntry> entries)
    {
        builder.AppendLine("    private static readonly ProTranslateGeneratedTranslationEntry[] s_entries = new ProTranslateGeneratedTranslationEntry[]");
        builder.AppendLine("    {");

        foreach (ProviderEntry entry in entries)
        {
            builder.Append("        new ProTranslateGeneratedTranslationEntry(");
            builder.Append(FormatStringLiteral(entry.Key));
            builder.Append(", ");
            builder.Append(entry.Culture is null ? "null" : FormatStringLiteral(entry.Culture));
            builder.Append(", ");
            builder.Append(FormatStringLiteral(entry.Value));
            builder.AppendLine("),");
        }

        builder.AppendLine("    };");
    }

    private static void AppendStringArray(StringBuilder builder, string fieldName, ImmutableArray<string> values)
    {
        builder.Append("    private static readonly string[] ");
        builder.Append(fieldName);
        builder.AppendLine(" = new string[]");
        builder.AppendLine("    {");

        foreach (string value in values)
        {
            builder.Append("        ");
            builder.Append(FormatStringLiteral(value));
            builder.AppendLine(",");
        }

        builder.AppendLine("    };");
    }

    private static void AppendIntArray(StringBuilder builder, ImmutableArray<int> values)
    {
        if (values.IsDefaultOrEmpty)
        {
            builder.Append("global::System.Array.Empty<int>()");
            return;
        }

        builder.Append("new int[] { ");
        for (int i = 0; i < values.Length; i++)
        {
            if (i > 0)
            {
                builder.Append(", ");
            }

            builder.Append(values[i].ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        builder.Append(" }");
    }

    private static CatalogFile ParseCatalogFile(AdditionalText file, System.Threading.CancellationToken cancellationToken)
    {
        SourceText? text = file.GetText(cancellationToken);
        if (text is null)
        {
            return new CatalogFile(file.Path, ImmutableArray<KeyEntry>.Empty, ImmutableArray<Diagnostic>.Empty);
        }

        if (IsResxCatalogFile(file.Path))
        {
            return ParseResxCatalogFile(file.Path, text);
        }

        if (IsAndroidResourceCatalogFile(file.Path))
        {
            return ParseAndroidCatalogFile(file.Path, text);
        }

        if (IsXliffCatalogFile(file.Path))
        {
            return ParseXliffCatalogFile(file.Path, text);
        }

        if (IsPoCatalogFile(file.Path))
        {
            return ParsePoCatalogFile(file.Path, text);
        }

        if (IsDelimitedCatalogFile(file.Path))
        {
            return ParseDelimitedCatalogFile(file.Path, text);
        }

        if (IsAppleStringsCatalogFile(file.Path))
        {
            return ParseAppleStringsCatalogFile(file.Path, text);
        }

        if (IsAppleStringsdictCatalogFile(file.Path))
        {
            return ParseAppleStringsdictCatalogFile(file.Path, text);
        }

        if (IsAppleXcstringsCatalogFile(file.Path))
        {
            return ParseAppleXcstringsCatalogFile(file.Path, text);
        }

        if (!IsJsonCatalogFile(file.Path))
        {
            return ParseTextCatalogFile(file.Path, text);
        }

        string content = text.ToString();
        int firstNonWhitespace = 0;
        while (firstNonWhitespace < content.Length && char.IsWhiteSpace(content[firstNonWhitespace]))
        {
            firstNonWhitespace++;
        }

        if (firstNonWhitespace >= content.Length || content[firstNonWhitespace] != '{')
        {
            return new CatalogFile(
                file.Path,
                ImmutableArray<KeyEntry>.Empty,
                ImmutableArray.Create(CreateInvalidJsonDiagnostic(file.Path, text, firstNonWhitespace, "Expected root object.")));
        }

        bool isArbCatalogFile = IsArbCatalogFile(file.Path);
        string? culture = null;
        if (isArbCatalogFile && TryFindJsonPropertyString(content, "@@locale", 0, content.Length, out string arbLocale))
        {
            culture = arbLocale;
        }

        return JsonCatalogParser.Parse(file.Path, text, InvalidJsonDescriptor, isArbCatalogFile, culture);
    }

    private static CatalogFile ParseTextCatalogFile(string path, SourceText text)
    {
        var keys = ImmutableArray.CreateBuilder<KeyEntry>();

        foreach (TextLine line in text.Lines)
        {
            string key = line.ToString().Trim();
            if (key.Length == 0 || key.StartsWith("#", StringComparison.Ordinal))
            {
                continue;
            }

            int offset = line.ToString().IndexOf(key, StringComparison.Ordinal);
            int position = line.Start + Math.Max(0, offset);
            keys.Add(new KeyEntry(key, path, text, position));
        }

        return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
    }

    private static CatalogFile ParseResxCatalogFile(string path, SourceText text)
    {
        try
        {
            XDocument document = XDocument.Parse(text.ToString(), LoadOptions.PreserveWhitespace);
            var keys = ImmutableArray.CreateBuilder<KeyEntry>();
            string? culture = InferResxCulture(path);

            foreach (XElement data in document.Descendants().Where(static element => element.Name.LocalName == "data"))
            {
                string? key = data.Attribute("name")?.Value;
                string? value = data.Elements().FirstOrDefault(static element => element.Name.LocalName == "value")?.Value;
                if (string.IsNullOrWhiteSpace(key) || value is null)
                {
                    continue;
                }

                keys.Add(CreateKeyEntry(path, text, key!, value, culture));
            }

            return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
        }
        catch (Exception ex) when (ex is System.Xml.XmlException or InvalidOperationException)
        {
            return CreateInvalidCatalogFile(path, text, ex.Message);
        }
    }

    private static CatalogFile ParseAndroidCatalogFile(string path, SourceText text)
    {
        try
        {
            XDocument document = XDocument.Parse(text.ToString(), LoadOptions.PreserveWhitespace);
            var keys = ImmutableArray.CreateBuilder<KeyEntry>();
            string? culture = InferAndroidCulture(path);

            foreach (XElement element in (document.Root?.Elements() ?? Enumerable.Empty<XElement>()))
            {
                string? key = element.Attribute("name")?.Value;
                if (string.IsNullOrWhiteSpace(key))
                {
                    continue;
                }

                if (element.Name.LocalName == "string")
                {
                    keys.Add(CreateKeyEntry(path, text, key!, element.Value, culture));
                }
                else if (element.Name.LocalName == "plurals")
                {
                    foreach (XElement item in element.Elements().Where(static child => child.Name.LocalName == "item"))
                    {
                        string? quantity = item.Attribute("quantity")?.Value;
                        if (!string.IsNullOrWhiteSpace(quantity))
                        {
                            keys.Add(CreateKeyEntry(path, text, key + "." + quantity, item.Value, culture));
                        }
                    }
                }
                else if (element.Name.LocalName == "string-array")
                {
                    int index = 0;
                    foreach (XElement item in element.Elements().Where(static child => child.Name.LocalName == "item"))
                    {
                        keys.Add(CreateKeyEntry(path, text, key + "[" + index.ToString(System.Globalization.CultureInfo.InvariantCulture) + "]", item.Value, culture));
                        index++;
                    }
                }
            }

            return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
        }
        catch (Exception ex) when (ex is System.Xml.XmlException or InvalidOperationException)
        {
            return CreateInvalidCatalogFile(path, text, ex.Message);
        }
    }

    private static CatalogFile ParseXliffCatalogFile(string path, SourceText text)
    {
        try
        {
            XDocument document = XDocument.Parse(text.ToString(), LoadOptions.PreserveWhitespace);
            XElement root = document.Root ?? throw new InvalidOperationException("XLIFF document is missing a root element.");
            var keys = ImmutableArray.CreateBuilder<KeyEntry>();
            string version = root.Attribute("version")?.Value ?? string.Empty;

            if (version.StartsWith("1.", StringComparison.Ordinal))
            {
                foreach (XElement file in root.Descendants().Where(static element => element.Name.LocalName == "file"))
                {
                    string? culture = file.Attribute("target-language")?.Value;
                    int index = 0;
                    foreach (XElement unit in file.Descendants().Where(static element => element.Name.LocalName == "trans-unit"))
                    {
                        string key = unit.Attribute("resname")?.Value
                            ?? unit.Attribute("id")?.Value
                            ?? "TransUnit" + index.ToString(System.Globalization.CultureInfo.InvariantCulture);
                        string? target = unit.Elements().FirstOrDefault(static element => element.Name.LocalName == "target")?.Value;
                        string? source = unit.Elements().FirstOrDefault(static element => element.Name.LocalName == "source")?.Value;
                        keys.Add(CreateKeyEntry(path, text, key, target ?? source ?? string.Empty, culture));
                        index++;
                    }
                }
            }
            else
            {
                string? culture = root.Attribute("trgLang")?.Value;
                int index = 0;
                foreach (XElement unit in root.Descendants().Where(static element => element.Name.LocalName == "unit"))
                {
                    string key = unit.Attribute("name")?.Value
                        ?? unit.Attribute("id")?.Value
                        ?? "Unit" + index.ToString(System.Globalization.CultureInfo.InvariantCulture);
                    foreach (XElement segment in unit.Descendants().Where(static element => element.Name.LocalName == "segment"))
                    {
                        string? target = segment.Elements().FirstOrDefault(static element => element.Name.LocalName == "target")?.Value;
                        string? source = segment.Elements().FirstOrDefault(static element => element.Name.LocalName == "source")?.Value;
                        keys.Add(CreateKeyEntry(path, text, key, target ?? source ?? string.Empty, culture));
                    }

                    index++;
                }
            }

            return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
        }
        catch (Exception ex) when (ex is System.Xml.XmlException or InvalidOperationException)
        {
            return CreateInvalidCatalogFile(path, text, ex.Message);
        }
    }

    private static CatalogFile ParsePoCatalogFile(string path, SourceText text)
    {
        var keys = ImmutableArray.CreateBuilder<KeyEntry>();
        string? culture = InferCultureFromPath(path, ".po") ?? InferCultureFromPath(path, ".pot");

        foreach (GeneratorPoEntry entry in ParsePoEntries(text.ToString()))
        {
            if (entry.MsgId.Length == 0)
            {
                string headerCulture = ReadPoHeaderLanguage(entry.MsgStr);
                if (headerCulture.Length > 0)
                {
                    culture = headerCulture;
                }

                continue;
            }

            string key = entry.Context is null ? entry.MsgId : entry.Context + "\u0004" + entry.MsgId;
            if (entry.PluralTranslations.Count == 0)
            {
                keys.Add(CreateKeyEntry(path, text, key, entry.MsgStr.Length == 0 ? entry.MsgId : entry.MsgStr, culture));
            }
            else
            {
                int pluralFormCount = entry.PluralTranslations.Keys.DefaultIfEmpty(-1).Max() + 1;
                foreach (KeyValuePair<int, string> plural in entry.PluralTranslations.OrderBy(static value => value.Key))
                {
                    string category = GetPoPluralCategory(plural.Key, pluralFormCount);
                    keys.Add(CreateKeyEntry(path, text, key + "." + category, plural.Value, culture));
                }
            }
        }

        return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
    }

    private static CatalogFile ParseDelimitedCatalogFile(string path, SourceText text)
    {
        char delimiter = path.EndsWith(".tsv", StringComparison.OrdinalIgnoreCase) ? '\t' : ',';
        List<string[]> rows = ParseDelimitedRows(text.ToString(), delimiter);
        if (rows.Count == 0)
        {
            return new CatalogFile(path, ImmutableArray<KeyEntry>.Empty, ImmutableArray<Diagnostic>.Empty);
        }

        Dictionary<string, int> columns = rows[0]
            .Select(static (name, index) => new { Name = name.Trim().ToLowerInvariant(), Index = index })
            .ToDictionary(static item => item.Name, static item => item.Index, StringComparer.Ordinal);

        if (!columns.ContainsKey("key") || !columns.ContainsKey("value"))
        {
            return CreateInvalidCatalogFile(path, text, "Delimited translation catalogs require key and value columns.");
        }

        var keys = ImmutableArray.CreateBuilder<KeyEntry>();
        for (int i = 1; i < rows.Count; i++)
        {
            string[] row = rows[i];
            string key = GetColumn(row, columns, "key");
            if (key.Length == 0)
            {
                continue;
            }

            keys.Add(CreateKeyEntry(path, text, key, GetColumn(row, columns, "value"), GetColumn(row, columns, "culture", null)));
        }

        return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
    }

    private static CatalogFile ParseAppleStringsCatalogFile(string path, SourceText text)
    {
        var keys = ImmutableArray.CreateBuilder<KeyEntry>();
        string content = text.ToString();
        string? culture = InferAppleCulture(path);
        int index = 0;

        while (index < content.Length)
        {
            SkipAppleWhitespaceAndComments(content, ref index);
            if (index >= content.Length)
            {
                break;
            }

            int keyPosition = index;
            if (!TryReadAppleQuotedString(content, ref index, out string key))
            {
                break;
            }

            SkipAppleWhitespaceAndComments(content, ref index);
            if (index >= content.Length || content[index] != '=')
            {
                break;
            }

            index++;
            SkipAppleWhitespaceAndComments(content, ref index);
            if (!TryReadAppleQuotedString(content, ref index, out string value))
            {
                break;
            }

            keys.Add(new KeyEntry(key, path, text, keyPosition, value, culture));
            while (index < content.Length && content[index] != ';')
            {
                index++;
            }

            if (index < content.Length)
            {
                index++;
            }
        }

        return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
    }

    private static CatalogFile ParseAppleStringsdictCatalogFile(string path, SourceText text)
    {
        try
        {
            XDocument document = XDocument.Parse(text.ToString(), LoadOptions.PreserveWhitespace);
            XElement? dict = document.Root?.Elements().FirstOrDefault(static element => element.Name.LocalName == "dict");
            if (dict is null)
            {
                return new CatalogFile(path, ImmutableArray<KeyEntry>.Empty, ImmutableArray<Diagnostic>.Empty);
            }

            var keys = ImmutableArray.CreateBuilder<KeyEntry>();
            string? culture = InferAppleCulture(path);
            Dictionary<string, XElement> top = ReadPlistDict(dict);
            foreach (KeyValuePair<string, XElement> entry in top)
            {
                Dictionary<string, XElement> valueDict = ReadPlistDict(entry.Value);
                foreach (KeyValuePair<string, XElement> child in valueDict)
                {
                    if (child.Value.Name.LocalName != "dict")
                    {
                        continue;
                    }

                    Dictionary<string, XElement> pluralDict = ReadPlistDict(child.Value);
                    if (!pluralDict.TryGetValue("NSStringFormatSpecTypeKey", out XElement? spec)
                        || !string.Equals(spec.Value, "NSStringPluralRuleType", StringComparison.Ordinal))
                    {
                        continue;
                    }

                    foreach (string category in new[] { "zero", "one", "two", "few", "many", "other" })
                    {
                        if (pluralDict.TryGetValue(category, out XElement? localized))
                        {
                            keys.Add(CreateKeyEntry(path, text, entry.Key + "." + category, localized.Value, culture));
                        }
                    }
                }
            }

            return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
        }
        catch (Exception ex) when (ex is System.Xml.XmlException or InvalidOperationException)
        {
            return CreateInvalidCatalogFile(path, text, ex.Message);
        }
    }

    private static CatalogFile ParseAppleXcstringsCatalogFile(string path, SourceText text)
    {
        string content = text.ToString();
        if (!TryFindJsonPropertyObject(content, "strings", out int start, out int end))
        {
            return new CatalogFile(path, ImmutableArray<KeyEntry>.Empty, ImmutableArray<Diagnostic>.Empty);
        }

        var keys = ImmutableArray.CreateBuilder<KeyEntry>();
        int position = start + 1;
        while (position < end)
        {
            SkipJsonWhitespace(content, ref position);
            if (position >= end || content[position] == '}')
            {
                break;
            }

            int keyPosition = position;
            if (!TryReadJsonString(content, ref position, out string key))
            {
                break;
            }

            SkipJsonWhitespace(content, ref position);
            if (position >= end || content[position] != ':')
            {
                break;
            }

            position++;
            SkipJsonWhitespace(content, ref position);
            if (!TryReadJsonValueSpan(content, ref position, out int objectStart, out int objectEnd))
            {
                break;
            }

            ParseXcstringsLocalizations(path, text, content, key, keyPosition, objectStart, objectEnd, keys);
            SkipJsonWhitespace(content, ref position);
            if (position < end && content[position] == ',')
            {
                position++;
            }
        }

        return new CatalogFile(path, keys.ToImmutable(), ImmutableArray<Diagnostic>.Empty);
    }

    private static void ParseXcstringsLocalizations(
        string path,
        SourceText text,
        string content,
        string key,
        int keyPosition,
        int objectStart,
        int objectEnd,
        ImmutableArray<KeyEntry>.Builder keys)
    {
        if (!TryFindJsonPropertyObject(content, "localizations", objectStart, objectEnd, out int localizationsStart, out int localizationsEnd))
        {
            return;
        }

        int position = localizationsStart + 1;
        while (position < localizationsEnd)
        {
            SkipJsonWhitespace(content, ref position);
            if (position >= localizationsEnd || content[position] == '}')
            {
                break;
            }

            if (!TryReadJsonString(content, ref position, out string culture))
            {
                break;
            }

            SkipJsonWhitespace(content, ref position);
            if (position >= localizationsEnd || content[position] != ':')
            {
                break;
            }

            position++;
            SkipJsonWhitespace(content, ref position);
            if (!TryReadJsonValueSpan(content, ref position, out int localizationStart, out int localizationEnd))
            {
                break;
            }

            if (TryGetXcstringsStringUnitValue(content, localizationStart, localizationEnd, out string value))
            {
                keys.Add(new KeyEntry(key, path, text, keyPosition, value, culture));
            }

            ParseXcstringsVariationValues(path, text, content, key, keyPosition, culture, localizationStart, localizationEnd, keys);

            SkipJsonWhitespace(content, ref position);
            if (position < localizationsEnd && content[position] == ',')
            {
                position++;
            }
        }
    }

    private static bool TryGetXcstringsStringUnitValue(string content, int objectStart, int objectEnd, out string value)
    {
        if (TryFindJsonPropertyObject(content, "stringUnit", objectStart, objectEnd, out int unitStart, out int unitEnd)
            && TryFindJsonPropertyString(content, "value", unitStart, unitEnd, out value))
        {
            return true;
        }

        return TryFindJsonPropertyString(content, "value", objectStart, objectEnd, out value);
    }

    private static void ParseXcstringsVariationValues(
        string path,
        SourceText text,
        string content,
        string key,
        int keyPosition,
        string culture,
        int localizationStart,
        int localizationEnd,
        ImmutableArray<KeyEntry>.Builder keys)
    {
        if (!TryFindJsonPropertyObject(content, "variations", localizationStart, localizationEnd, out int variationsStart, out int variationsEnd))
        {
            return;
        }

        int dimensionPosition = variationsStart + 1;
        while (dimensionPosition < variationsEnd)
        {
            SkipJsonWhitespace(content, ref dimensionPosition);
            if (dimensionPosition >= variationsEnd || content[dimensionPosition] == '}')
            {
                break;
            }

            if (!TryReadJsonString(content, ref dimensionPosition, out _))
            {
                break;
            }

            SkipJsonWhitespace(content, ref dimensionPosition);
            if (dimensionPosition >= variationsEnd || content[dimensionPosition] != ':')
            {
                break;
            }

            dimensionPosition++;
            SkipJsonWhitespace(content, ref dimensionPosition);
            if (!TryReadJsonValueSpan(content, ref dimensionPosition, out int dimensionStart, out int dimensionEnd))
            {
                break;
            }

            ParseXcstringsVariationDimension(path, text, content, key, keyPosition, culture, dimensionStart, dimensionEnd, keys);
            SkipJsonWhitespace(content, ref dimensionPosition);
            if (dimensionPosition < variationsEnd && content[dimensionPosition] == ',')
            {
                dimensionPosition++;
            }
        }
    }

    private static void ParseXcstringsVariationDimension(
        string path,
        SourceText text,
        string content,
        string key,
        int keyPosition,
        string culture,
        int dimensionStart,
        int dimensionEnd,
        ImmutableArray<KeyEntry>.Builder keys)
    {
        int variationPosition = dimensionStart + 1;
        while (variationPosition < dimensionEnd)
        {
            SkipJsonWhitespace(content, ref variationPosition);
            if (variationPosition >= dimensionEnd || content[variationPosition] == '}')
            {
                break;
            }

            if (!TryReadJsonString(content, ref variationPosition, out string variationName))
            {
                break;
            }

            SkipJsonWhitespace(content, ref variationPosition);
            if (variationPosition >= dimensionEnd || content[variationPosition] != ':')
            {
                break;
            }

            variationPosition++;
            SkipJsonWhitespace(content, ref variationPosition);
            if (!TryReadJsonValueSpan(content, ref variationPosition, out int variationStart, out int variationEnd))
            {
                break;
            }

            if (TryGetXcstringsStringUnitValue(content, variationStart, variationEnd, out string value))
            {
                keys.Add(new KeyEntry(key + "." + variationName, path, text, keyPosition, value, culture));
            }

            SkipJsonWhitespace(content, ref variationPosition);
            if (variationPosition < dimensionEnd && content[variationPosition] == ',')
            {
                variationPosition++;
            }
        }
    }

    private static KeyEntry CreateKeyEntry(string path, SourceText text, string key, string value, string? culture = null)
    {
        string content = text.ToString();
        int position = content.IndexOf(key, StringComparison.Ordinal);
        return new KeyEntry(key, path, text, Math.Max(0, position), value, culture);
    }

    private static CatalogFile CreateInvalidCatalogFile(string path, SourceText text, string message) =>
        new(
            path,
            ImmutableArray<KeyEntry>.Empty,
            ImmutableArray.Create(CreateInvalidJsonDiagnostic(path, text, 0, message)));

    private static string? InferResxCulture(string path) => InferCultureFromPath(path, ".resx");

    private static string? InferCultureFromPath(string path, string extension)
    {
        string fileName = Path.GetFileName(path);
        if (!fileName.EndsWith(extension, StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        string withoutExtension = fileName.Substring(0, fileName.Length - extension.Length);
        int separator = withoutExtension.LastIndexOf('.');
        return separator < 0 || separator == withoutExtension.Length - 1
            ? null
            : withoutExtension.Substring(separator + 1);
    }

    private static string? InferAndroidCulture(string path)
    {
        string? directory = Path.GetFileName(Path.GetDirectoryName(path));
        if (directory is null || !directory.StartsWith("values-", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        string qualifier = directory.Substring("values-".Length);
        if (qualifier.StartsWith("b+", StringComparison.OrdinalIgnoreCase))
        {
            string[] bcp47Parts = qualifier.Split(new[] { '+' })
                .Where(static part => part.Length > 0)
                .ToArray();
            return bcp47Parts.Length > 1 ? NormalizeAndroidBcp47Culture(bcp47Parts.Skip(1)) : null;
        }

        string[] parts = qualifier.Split(new[] { '-' })
            .Where(static part => part.Length > 0)
            .ToArray();
        if (parts.Length == 0 || !IsAndroidLanguageQualifier(parts[0]))
        {
            return null;
        }

        var cultureParts = new List<string> { parts[0].ToLowerInvariant() };
        for (int i = 1; i < parts.Length; i++)
        {
            string part = parts[i];
            if (part.Length == 4 && part.All(char.IsLetter))
            {
                cultureParts.Add(char.ToUpperInvariant(part[0]) + part.Substring(1).ToLowerInvariant());
            }
            else if (part.Length == 3 && (part[0] == 'r' || part[0] == 'R') && part.Substring(1).All(char.IsLetterOrDigit))
            {
                cultureParts.Add(part.Substring(1).ToUpperInvariant());
            }
            else
            {
                break;
            }
        }

        return string.Join("-", cultureParts);
    }

    private static bool IsAndroidLanguageQualifier(string value) =>
        (value.Length == 2 || value.Length == 3) && value.All(char.IsLetter);

    private static string NormalizeAndroidBcp47Culture(IEnumerable<string> parts)
    {
        var normalized = new List<string>();
        int index = 0;
        foreach (string part in parts)
        {
            if (part.Length == 0)
            {
                continue;
            }

            if (index == 0)
            {
                normalized.Add(part.ToLowerInvariant());
            }
            else if (part.Length == 2 || part.Length == 3)
            {
                normalized.Add(part.ToUpperInvariant());
            }
            else if (part.Length == 4)
            {
                normalized.Add(char.ToUpperInvariant(part[0]) + part.Substring(1).ToLowerInvariant());
            }
            else
            {
                normalized.Add(part);
            }

            index++;
        }

        return normalized.Count == 0 ? string.Empty : string.Join("-", normalized);
    }

    private static string GetPoPluralCategory(int pluralIndex, int pluralFormCount)
    {
        if (pluralFormCount <= 2)
        {
            return pluralIndex == 0 ? "one" : "other";
        }

        return pluralFormCount switch
        {
            3 => pluralIndex switch
            {
                0 => "one",
                1 => "few",
                2 => "many",
                _ => "plural" + pluralIndex.ToString(System.Globalization.CultureInfo.InvariantCulture)
            },
            4 => pluralIndex switch
            {
                0 => "one",
                1 => "two",
                2 => "few",
                3 => "other",
                _ => "plural" + pluralIndex.ToString(System.Globalization.CultureInfo.InvariantCulture)
            },
            6 => pluralIndex switch
            {
                0 => "zero",
                1 => "one",
                2 => "two",
                3 => "few",
                4 => "many",
                5 => "other",
                _ => "plural" + pluralIndex.ToString(System.Globalization.CultureInfo.InvariantCulture)
            },
            _ => "plural" + pluralIndex.ToString(System.Globalization.CultureInfo.InvariantCulture)
        };
    }

    private static string? InferAppleCulture(string path)
    {
        string? directory = Path.GetFileName(Path.GetDirectoryName(path));
        if (directory is not null && directory.EndsWith(".lproj", StringComparison.OrdinalIgnoreCase))
        {
            return directory.Substring(0, directory.Length - ".lproj".Length);
        }

        return InferCultureFromPath(path, Path.GetExtension(path));
    }

    private static Dictionary<string, XElement> ReadPlistDict(XElement dict)
    {
        var values = new Dictionary<string, XElement>(StringComparer.Ordinal);
        XElement? key = null;
        foreach (XElement child in dict.Elements())
        {
            if (child.Name.LocalName == "key")
            {
                key = child;
                continue;
            }

            if (key is not null)
            {
                values[key.Value] = child;
                key = null;
            }
        }

        return values;
    }

    private static IEnumerable<GeneratorPoEntry> ParsePoEntries(string content)
    {
        var entries = new List<GeneratorPoEntry>();
        var current = new GeneratorPoEntry();
        string? active = null;
        int? pluralIndex = null;

        foreach (string rawLine in content.Replace("\r\n", "\n").Split('\n'))
        {
            string line = rawLine.Trim();
            if (line.Length == 0)
            {
                if (current.HasContent)
                {
                    entries.Add(current);
                    current = new GeneratorPoEntry();
                    active = null;
                    pluralIndex = null;
                }

                continue;
            }

            if (line.StartsWith("msgctxt", StringComparison.Ordinal))
            {
                current.Context = ReadPoString(line.Substring("msgctxt".Length).Trim());
                active = "msgctxt";
                pluralIndex = null;
            }
            else if (line.StartsWith("msgid_plural", StringComparison.Ordinal))
            {
                current.MsgIdPlural = ReadPoString(line.Substring("msgid_plural".Length).Trim());
                active = "msgid_plural";
                pluralIndex = null;
            }
            else if (line.StartsWith("msgid", StringComparison.Ordinal))
            {
                current.MsgId = ReadPoString(line.Substring("msgid".Length).Trim());
                active = "msgid";
                pluralIndex = null;
            }
            else if (line.StartsWith("msgstr[", StringComparison.Ordinal))
            {
                int end = line.IndexOf(']');
                if (end > 7 && int.TryParse(line.Substring(7, end - 7), out int parsedIndex))
                {
                    pluralIndex = parsedIndex;
                    current.PluralTranslations[parsedIndex] = ReadPoString(line.Substring(end + 1).Trim());
                    active = "msgstr";
                }
            }
            else if (line.StartsWith("msgstr", StringComparison.Ordinal))
            {
                current.MsgStr = ReadPoString(line.Substring("msgstr".Length).Trim());
                active = "msgstr";
                pluralIndex = null;
            }
            else if (line.StartsWith("\"", StringComparison.Ordinal) && active is not null)
            {
                string fragment = ReadPoString(line);
                if (active == "msgctxt")
                {
                    current.Context += fragment;
                }
                else if (active == "msgid")
                {
                    current.MsgId += fragment;
                }
                else if (active == "msgid_plural")
                {
                    current.MsgIdPlural += fragment;
                }
                else if (active == "msgstr" && pluralIndex is not null)
                {
                    current.PluralTranslations[pluralIndex.Value] += fragment;
                }
                else if (active == "msgstr")
                {
                    current.MsgStr += fragment;
                }
            }
        }

        if (current.HasContent)
        {
            entries.Add(current);
        }

        return entries;
    }

    private static string ReadPoHeaderLanguage(string header)
    {
        foreach (string line in header.Split('\n'))
        {
            if (line.StartsWith("Language:", StringComparison.OrdinalIgnoreCase))
            {
                return line.Substring("Language:".Length).Trim();
            }
        }

        return string.Empty;
    }

    private static string ReadPoString(string token)
    {
        token = token.Trim();
        if (token.Length < 2 || token[0] != '"' || token[token.Length - 1] != '"')
        {
            return string.Empty;
        }

        string inner = token.Substring(1, token.Length - 2);
        var builder = new StringBuilder(inner.Length);
        for (int i = 0; i < inner.Length; i++)
        {
            char current = inner[i];
            if (current == '\\' && i + 1 < inner.Length)
            {
                char escaped = inner[++i];
                builder.Append(escaped switch
                {
                    'n' => '\n',
                    'r' => '\r',
                    't' => '\t',
                    '"' => '"',
                    '\\' => '\\',
                    _ => escaped
                });
            }
            else
            {
                builder.Append(current);
            }
        }

        return builder.ToString();
    }

    private static List<string[]> ParseDelimitedRows(string content, char delimiter)
    {
        var rows = new List<string[]>();
        var row = new List<string>();
        var field = new StringBuilder();
        bool quoted = false;

        for (int i = 0; i < content.Length; i++)
        {
            char current = content[i];
            if (quoted)
            {
                if (current == '"' && i + 1 < content.Length && content[i + 1] == '"')
                {
                    field.Append('"');
                    i++;
                }
                else if (current == '"')
                {
                    quoted = false;
                }
                else
                {
                    field.Append(current);
                }

                continue;
            }

            if (current == '"')
            {
                quoted = true;
            }
            else if (current == delimiter)
            {
                row.Add(field.ToString());
                field.Clear();
            }
            else if (current == '\n')
            {
                row.Add(field.ToString());
                field.Clear();
                rows.Add(row.ToArray());
                row.Clear();
            }
            else if (current != '\r')
            {
                field.Append(current);
            }
        }

        row.Add(field.ToString());
        if (row.Count > 1 || row[0].Length > 0)
        {
            rows.Add(row.ToArray());
        }

        return rows;
    }

    private static string GetColumn(string[] row, Dictionary<string, int> columns, string name, string? fallback = "")
    {
        return columns.TryGetValue(name, out int index) && index < row.Length ? row[index] : fallback ?? string.Empty;
    }

    private static void SkipAppleWhitespaceAndComments(string text, ref int index)
    {
        while (index < text.Length)
        {
            if (char.IsWhiteSpace(text[index]))
            {
                index++;
                continue;
            }

            if (index + 1 < text.Length && text[index] == '/' && text[index + 1] == '*')
            {
                int end = text.IndexOf("*/", index + 2, StringComparison.Ordinal);
                index = end < 0 ? text.Length : end + 2;
                continue;
            }

            if (index + 1 < text.Length && text[index] == '/' && text[index + 1] == '/')
            {
                int end = text.IndexOf('\n', index + 2);
                index = end < 0 ? text.Length : end + 1;
                continue;
            }

            break;
        }
    }

    private static bool TryReadAppleQuotedString(string text, ref int index, out string value)
    {
        value = string.Empty;
        if (index >= text.Length || text[index] != '"')
        {
            return false;
        }

        return TryReadJsonString(text, ref index, out value);
    }

    private static bool TryFindJsonPropertyObject(string content, string propertyName, out int start, out int end) =>
        TryFindJsonPropertyObject(content, propertyName, 0, content.Length, out start, out end);

    private static bool TryFindJsonPropertyObject(string content, string propertyName, int searchStart, int searchEnd, out int start, out int end)
    {
        start = 0;
        end = 0;
        int position = searchStart;
        while (position < searchEnd)
        {
            SkipJsonWhitespace(content, ref position);
            if (!TryReadJsonString(content, ref position, out string name))
            {
                position++;
                continue;
            }

            SkipJsonWhitespace(content, ref position);
            if (position >= searchEnd || content[position] != ':')
            {
                continue;
            }

            position++;
            SkipJsonWhitespace(content, ref position);
            if (name == propertyName && position < searchEnd && content[position] == '{')
            {
                int valuePosition = position;
                if (TryReadJsonValueSpan(content, ref valuePosition, out start, out end))
                {
                    return true;
                }
            }

            TryReadJsonValueSpan(content, ref position, out _, out _);
        }

        return false;
    }

    private static bool TryFindJsonPropertyString(string content, string propertyName, int searchStart, int searchEnd, out string value)
    {
        value = string.Empty;
        int position = searchStart;
        while (position < searchEnd)
        {
            SkipJsonWhitespace(content, ref position);
            if (!TryReadJsonString(content, ref position, out string name))
            {
                position++;
                continue;
            }

            SkipJsonWhitespace(content, ref position);
            if (position >= searchEnd || content[position] != ':')
            {
                continue;
            }

            position++;
            SkipJsonWhitespace(content, ref position);
            if (name == propertyName && TryReadJsonString(content, ref position, out value))
            {
                return true;
            }

            TryReadJsonValueSpan(content, ref position, out _, out _);
        }

        return false;
    }

    private static bool TryReadJsonValueSpan(string content, ref int position, out int start, out int end)
    {
        SkipJsonWhitespace(content, ref position);
        start = position;
        end = position;
        if (position >= content.Length)
        {
            return false;
        }

        if (content[position] == '{')
        {
            return TryReadBalancedJson(content, ref position, '{', '}', out start, out end);
        }

        if (content[position] == '[')
        {
            return TryReadBalancedJson(content, ref position, '[', ']', out start, out end);
        }

        if (content[position] == '"')
        {
            if (!TryReadJsonString(content, ref position, out _))
            {
                return false;
            }

            end = position;
            return true;
        }

        while (position < content.Length && content[position] != ',' && content[position] != '}' && content[position] != ']')
        {
            position++;
        }

        end = position;
        return true;
    }

    private static bool TryReadBalancedJson(string content, ref int position, char open, char close, out int start, out int end)
    {
        start = position;
        end = position;
        int depth = 0;
        bool inString = false;
        bool escaped = false;

        while (position < content.Length)
        {
            char current = content[position++];
            if (inString)
            {
                if (escaped)
                {
                    escaped = false;
                }
                else if (current == '\\')
                {
                    escaped = true;
                }
                else if (current == '"')
                {
                    inString = false;
                }

                continue;
            }

            if (current == '"')
            {
                inString = true;
            }
            else if (current == open)
            {
                depth++;
            }
            else if (current == close)
            {
                depth--;
                if (depth == 0)
                {
                    end = position;
                    return true;
                }
            }
        }

        return false;
    }

    private static bool TryReadJsonString(string content, ref int position, out string value)
    {
        value = string.Empty;
        if (position >= content.Length || content[position] != '"')
        {
            return false;
        }

        position++;
        var builder = new StringBuilder();
        while (position < content.Length)
        {
            char current = content[position++];
            if (current == '"')
            {
                value = builder.ToString();
                return true;
            }

            if (current == '\\' && position < content.Length)
            {
                char escaped = content[position++];
                builder.Append(escaped switch
                {
                    'b' => '\b',
                    'f' => '\f',
                    'n' => '\n',
                    'r' => '\r',
                    't' => '\t',
                    '"' => '"',
                    '\\' => '\\',
                    '/' => '/',
                    'u' when TryReadUnicodeEscape(content, ref position, out char unicodeCharacter) => unicodeCharacter,
                    _ => escaped
                });
            }
            else
            {
                builder.Append(current);
            }
        }

        return false;
    }

    private static bool TryReadUnicodeEscape(string content, ref int position, out char value)
    {
        value = '\0';
        if (position + 4 > content.Length)
        {
            return false;
        }

        int codePoint = 0;
        for (int i = 0; i < 4; i++)
        {
            int digit = HexValue(content[position + i]);
            if (digit < 0)
            {
                return false;
            }

            codePoint = (codePoint << 4) + digit;
        }

        position += 4;
        value = (char)codePoint;
        return true;
    }

    private static int HexValue(char character)
    {
        if (character >= '0' && character <= '9')
        {
            return character - '0';
        }

        if (character >= 'a' && character <= 'f')
        {
            return character - 'a' + 10;
        }

        if (character >= 'A' && character <= 'F')
        {
            return character - 'A' + 10;
        }

        return -1;
    }

    private static void SkipJsonWhitespace(string content, ref int position)
    {
        while (position < content.Length && char.IsWhiteSpace(content[position]))
        {
            position++;
        }
    }

    private static CatalogModel CreateCatalogModel(ImmutableArray<CatalogFile> files)
    {
        var diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        var allKeys = ImmutableArray.CreateBuilder<string>();

        foreach (CatalogFile file in files.OrderBy(file => file.Path, StringComparer.OrdinalIgnoreCase))
        {
            diagnostics.AddRange(file.Diagnostics);
            allKeys.AddRange(file.Keys.Select(key => key.Key));

            foreach (IGrouping<string, KeyEntry> group in file.Keys.GroupBy(key => key.Key, StringComparer.Ordinal))
            {
                KeyEntry[] duplicates = group.Skip(1).ToArray();
                foreach (KeyEntry duplicate in duplicates)
                {
                    diagnostics.Add(Diagnostic.Create(
                        DuplicateKeyDescriptor,
                        duplicate.Location,
                        duplicate.Key,
                        Path.GetFileName(file.Path)));
                }
            }
        }

        ImmutableArray<string> keys = allKeys
            .Distinct(StringComparer.Ordinal)
            .OrderBy(key => key, StringComparer.Ordinal)
            .ToImmutableArray();

        ImmutableArray<ManifestEntry> manifestEntries = files
            .SelectMany(static file => file.Keys.Select(static key => key.ToManifestEntry()))
            .OrderBy(static entry => entry.Key, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Culture ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(static entry => entry.SourceFile, StringComparer.Ordinal)
            .ThenBy(static entry => string.Join(",", entry.PlaceholderIndexes.Select(static value => value.ToString(System.Globalization.CultureInfo.InvariantCulture)).ToArray()), StringComparer.Ordinal)
            .ToImmutableArray();

        ImmutableArray<string> cultures = manifestEntries
            .Select(static entry => entry.Culture)
            .Where(static culture => culture is not null)
            .Select(static culture => culture!)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static culture => culture, StringComparer.Ordinal)
            .ToImmutableArray();

        ImmutableArray<string> sourceFiles = manifestEntries
            .Select(static entry => entry.SourceFile)
            .Distinct(StringComparer.Ordinal)
            .OrderBy(static sourceFile => sourceFile, StringComparer.Ordinal)
            .ToImmutableArray();

        ImmutableArray<ProviderEntry> providerEntries = files
            .SelectMany(static file => file.Keys)
            .Where(static key => key.Value is not null)
            .Select(static key => new ProviderEntry(key.Key, key.Culture, key.Value!))
            .OrderBy(static entry => entry.Key, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Culture ?? string.Empty, StringComparer.Ordinal)
            .ThenBy(static entry => entry.Value, StringComparer.Ordinal)
            .ToImmutableArray();

        return new CatalogModel(keys, manifestEntries, providerEntries, cultures, sourceFiles, diagnostics.ToImmutable());
    }

    private static ImmutableArray<KeyIdentifier> CreateIdentifiers(ImmutableArray<string> keys)
    {
        var baseNames = keys
            .Select(static key => new KeyIdentifier(key, CreateIdentifier(key)))
            .ToArray();

        var collisions = baseNames
            .GroupBy(identifier => identifier.Name, StringComparer.Ordinal)
            .Where(group => group.Count() > 1)
            .Select(group => group.Key)
            .ToImmutableHashSet(StringComparer.Ordinal);

        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var identifiers = ImmutableArray.CreateBuilder<KeyIdentifier>(baseNames.Length);

        foreach (KeyIdentifier identifier in baseNames)
        {
            string name = identifier.Name;
            if (collisions.Contains(name))
            {
                name = name + "_" + ComputeStableHash(identifier.Key);
            }

            while (!usedNames.Add(name))
            {
                name = name + "_Key";
            }

            identifiers.Add(new KeyIdentifier(identifier.Key, name));
        }

        return identifiers.ToImmutable();
    }

    private static bool IsCatalogFile(string path) =>
        path.EndsWith(".protranslate.keys.txt", StringComparison.OrdinalIgnoreCase)
        || IsJsonCatalogFile(path)
        || IsResxCatalogFile(path)
        || IsAndroidResourceCatalogFile(path)
        || IsXliffCatalogFile(path)
        || IsPoCatalogFile(path)
        || IsDelimitedCatalogFile(path)
        || IsAppleStringsCatalogFile(path)
        || IsAppleStringsdictCatalogFile(path)
        || IsAppleXcstringsCatalogFile(path);

    private static bool IsJsonCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.EndsWith(".protranslate.json", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".i18next.json", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".i18n.json", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".arb", StringComparison.OrdinalIgnoreCase)
            || (fileName.StartsWith("Strings.", StringComparison.OrdinalIgnoreCase)
                && fileName.EndsWith(".json", StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsArbCatalogFile(string path) =>
        Path.GetFileName(path).EndsWith(".arb", StringComparison.OrdinalIgnoreCase);

    private static bool IsResxCatalogFile(string path) =>
        Path.GetFileName(path).EndsWith(".resx", StringComparison.OrdinalIgnoreCase);

    private static bool IsAndroidResourceCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.Equals("strings.xml", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".strings.xml", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsXliffCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.EndsWith(".xlf", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".xliff", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsPoCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.EndsWith(".po", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".pot", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsDelimitedCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.EndsWith(".csv", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".tsv", StringComparison.OrdinalIgnoreCase);
    }

    private static bool IsAppleXcstringsCatalogFile(string path) =>
        Path.GetFileName(path).EndsWith(".xcstrings", StringComparison.OrdinalIgnoreCase);

    private static bool IsAppleStringsdictCatalogFile(string path) =>
        Path.GetFileName(path).EndsWith(".stringsdict", StringComparison.OrdinalIgnoreCase);

    private static bool IsAppleStringsCatalogFile(string path)
    {
        string fileName = Path.GetFileName(path);
        return fileName.EndsWith(".strings", StringComparison.OrdinalIgnoreCase)
            && !IsAppleStringsdictCatalogFile(path)
            && !IsAppleXcstringsCatalogFile(path);
    }

    private static string? InferCulture(string path)
    {
        string fileName = Path.GetFileName(path);
        if ((fileName.EndsWith(".protranslate.json", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".i18next.json", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".i18n.json", StringComparison.OrdinalIgnoreCase)
                || fileName.EndsWith(".arb", StringComparison.OrdinalIgnoreCase))
            || !fileName.StartsWith("Strings.", StringComparison.OrdinalIgnoreCase)
            || !fileName.EndsWith(".json", StringComparison.OrdinalIgnoreCase))
        {
            return null;
        }

        const string prefix = "Strings.";
        const string suffix = ".json";
        string culture = fileName.Substring(prefix.Length, fileName.Length - prefix.Length - suffix.Length);
        return culture.Length == 0 ? null : culture;
    }

    private static ImmutableArray<int> ExtractPlaceholderIndexes(string value)
    {
        SortedSet<int>? indexes = null;

        for (int i = 0; i < value.Length; i++)
        {
            if (value[i] != '{')
            {
                continue;
            }

            if (i + 1 < value.Length && value[i + 1] == '{')
            {
                i++;
                continue;
            }

            int position = i + 1;
            while (position < value.Length && char.IsWhiteSpace(value[position]))
            {
                position++;
            }

            int digitStart = position;
            long index = 0;
            while (position < value.Length && char.IsDigit(value[position]))
            {
                index = (index * 10) + (value[position] - '0');
                if (index > int.MaxValue)
                {
                    break;
                }

                position++;
            }

            if (position == digitStart || index > int.MaxValue)
            {
                continue;
            }

            while (position < value.Length && char.IsWhiteSpace(value[position]))
            {
                position++;
            }

            if (position >= value.Length || (value[position] != '}' && value[position] != ',' && value[position] != ':'))
            {
                continue;
            }

            if (value[position] != '}' && !HasPlaceholderEnd(value, position + 1))
            {
                continue;
            }

            indexes ??= new SortedSet<int>();
            indexes.Add((int)index);
        }

        return indexes is null ? ImmutableArray<int>.Empty : indexes.ToImmutableArray();
    }

    private static bool HasPlaceholderEnd(string value, int start)
    {
        for (int i = start; i < value.Length; i++)
        {
            if (value[i] == '}' && i + 1 < value.Length && value[i + 1] == '}')
            {
                i++;
                continue;
            }

            if (value[i] == '}')
            {
                return true;
            }
        }

        return false;
    }

    private static string CreateIdentifier(string key)
    {
        var builder = new StringBuilder(key.Length);
        bool capitalizeNext = true;

        foreach (char character in key)
        {
            if (char.IsLetterOrDigit(character))
            {
                builder.Append(capitalizeNext ? char.ToUpperInvariant(character) : character);
                capitalizeNext = false;
            }
            else
            {
                capitalizeNext = true;
            }
        }

        if (builder.Length == 0 || char.IsDigit(builder[0]))
        {
            builder.Insert(0, '_');
        }

        string identifier = builder.ToString();
        return IsCSharpKeyword(identifier) ? "_" + identifier : identifier;
    }

    private static string FormatStringLiteral(string value)
    {
        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t") + "\"";
    }

    private static string ComputeStableHash(string value)
    {
        const uint offsetBasis = 2166136261;
        const uint prime = 16777619;

        uint hash = offsetBasis;
        foreach (char character in value)
        {
            hash ^= character;
            hash *= prime;
        }

        return hash.ToString("X8", System.Globalization.CultureInfo.InvariantCulture);
    }

    private static bool IsCSharpKeyword(string value)
    {
        switch (value)
        {
            case "abstract":
            case "as":
            case "base":
            case "bool":
            case "break":
            case "byte":
            case "case":
            case "catch":
            case "char":
            case "checked":
            case "class":
            case "const":
            case "continue":
            case "decimal":
            case "default":
            case "delegate":
            case "do":
            case "double":
            case "else":
            case "enum":
            case "event":
            case "explicit":
            case "extern":
            case "false":
            case "finally":
            case "fixed":
            case "float":
            case "for":
            case "foreach":
            case "goto":
            case "if":
            case "implicit":
            case "in":
            case "int":
            case "interface":
            case "internal":
            case "is":
            case "lock":
            case "long":
            case "namespace":
            case "new":
            case "null":
            case "object":
            case "operator":
            case "out":
            case "override":
            case "params":
            case "private":
            case "protected":
            case "public":
            case "readonly":
            case "ref":
            case "return":
            case "sbyte":
            case "sealed":
            case "short":
            case "sizeof":
            case "stackalloc":
            case "static":
            case "string":
            case "struct":
            case "switch":
            case "this":
            case "throw":
            case "true":
            case "try":
            case "typeof":
            case "uint":
            case "ulong":
            case "unchecked":
            case "unsafe":
            case "ushort":
            case "using":
            case "virtual":
            case "void":
            case "volatile":
            case "while":
                return true;
            default:
                return false;
        }
    }

    private sealed class JsonCatalogParser
    {
        private readonly string _path;
        private readonly SourceText _text;
        private readonly DiagnosticDescriptor _invalidJsonDescriptor;
        private readonly ImmutableArray<KeyEntry>.Builder _keys = ImmutableArray.CreateBuilder<KeyEntry>();
        private readonly ImmutableArray<Diagnostic>.Builder _diagnostics = ImmutableArray.CreateBuilder<Diagnostic>();
        private readonly bool _skipMetadataKeys;
        private readonly string? _culture;
        private string _content;
        private int _position;

        private JsonCatalogParser(string path, SourceText text, DiagnosticDescriptor invalidJsonDescriptor, bool skipMetadataKeys, string? culture)
        {
            _path = path;
            _text = text;
            _invalidJsonDescriptor = invalidJsonDescriptor;
            _skipMetadataKeys = skipMetadataKeys;
            _culture = string.IsNullOrWhiteSpace(culture) ? null : culture;
            _content = text.ToString();
        }

        public static CatalogFile Parse(string path, SourceText text, DiagnosticDescriptor invalidJsonDescriptor, bool skipMetadataKeys = false, string? culture = null)
        {
            var parser = new JsonCatalogParser(path, text, invalidJsonDescriptor, skipMetadataKeys, culture);
            parser.ParseRoot();
            return new CatalogFile(path, parser._keys.ToImmutable(), parser._diagnostics.ToImmutable());
        }

        private void ParseRoot()
        {
            SkipWhitespace();
            if (!TryConsume('{'))
            {
                AddInvalidJson("Expected root object.");
                return;
            }

            ParseObjectMembers(prefix: string.Empty);
            if (_diagnostics.Count > 0)
            {
                return;
            }

            SkipWhitespace();
            if (!IsEnd)
            {
                AddInvalidJson("Unexpected content after root object.");
            }
        }

        private void ParseObjectMembers(string prefix)
        {
            SkipWhitespace();
            if (TryConsume('}'))
            {
                return;
            }

            while (!IsEnd)
            {
                SkipWhitespace();
                int nameStart = _position;
                if (!TryParseString(out string? propertyName))
                {
                    AddInvalidJson("Expected property name.");
                    return;
                }

                SkipWhitespace();
                if (!TryConsume(':'))
                {
                    AddInvalidJson("Expected ':' after property name.");
                    return;
                }

                string key = prefix.Length == 0 ? propertyName : prefix + "." + propertyName;
                SkipWhitespace();

                if (_skipMetadataKeys && propertyName.StartsWith("@", StringComparison.Ordinal))
                {
                    if (!TrySkipJsonValue())
                    {
                        return;
                    }
                }
                else
                    if (TryConsume('{'))
                    {
                        ParseObjectMembers(key);
                    }
                    else if (Current == '"')
                    {
                        if (!TryParseString(out string? value))
                        {
                            return;
                        }

                        _keys.Add(new KeyEntry(key, _path, _text, nameStart, value, _culture));
                    }
                    else if (!TrySkipValue())
                    {
                        return;
                    }

                SkipWhitespace();
                if (TryConsume('}'))
                {
                    return;
                }

                if (!TryConsume(','))
                {
                    AddInvalidJson("Expected ',' or '}' after property value.");
                    return;
                }
            }

            AddInvalidJson("Unterminated object.");
        }

        private bool TryParseString(out string value)
        {
            value = string.Empty;
            if (!TryConsume('"'))
            {
                return false;
            }

            var builder = new StringBuilder();
            while (!IsEnd)
            {
                char character = _content[_position++];
                if (character == '"')
                {
                    value = builder.ToString();
                    return true;
                }

                if (character != '\\')
                {
                    builder.Append(character);
                    continue;
                }

                if (IsEnd)
                {
                    AddInvalidJson("Unterminated escape sequence.");
                    return false;
                }

                char escape = _content[_position++];
                switch (escape)
                {
                    case '"':
                    case '\\':
                    case '/':
                        builder.Append(escape);
                        break;
                    case 'b':
                        builder.Append('\b');
                        break;
                    case 'f':
                        builder.Append('\f');
                        break;
                    case 'n':
                        builder.Append('\n');
                        break;
                    case 'r':
                        builder.Append('\r');
                        break;
                    case 't':
                        builder.Append('\t');
                        break;
                    case 'u':
                        if (!TryParseUnicodeEscape(out char unicodeCharacter))
                        {
                            return false;
                        }

                        builder.Append(unicodeCharacter);
                        break;
                    default:
                        AddInvalidJson("Invalid string escape sequence.");
                        return false;
                }
            }

            AddInvalidJson("Unterminated string.");
            return false;
        }

        private bool TryParseUnicodeEscape(out char value)
        {
            value = '\0';
            if (_position + 4 > _content.Length)
            {
                AddInvalidJson("Incomplete unicode escape sequence.");
                return false;
            }

            int codePoint = 0;
            for (int i = 0; i < 4; i++)
            {
                int digit = HexValue(_content[_position + i]);
                if (digit < 0)
                {
                    AddInvalidJson("Invalid unicode escape sequence.");
                    return false;
                }

                codePoint = (codePoint << 4) + digit;
            }

            _position += 4;
            value = (char)codePoint;
            return true;
        }

        private bool TrySkipValue()
        {
            if (TryConsume('['))
            {
                return TrySkipArray();
            }

            if (TryConsume('{'))
            {
                return TrySkipObject();
            }

            if (TryConsumeLiteral("true") || TryConsumeLiteral("false") || TryConsumeLiteral("null"))
            {
                return true;
            }

            return TrySkipNumber();
        }

        private bool TrySkipJsonValue()
        {
            SkipWhitespace();
            if (IsEnd)
            {
                AddInvalidJson("Expected value.");
                return false;
            }

            if (Current == '"')
            {
                return TryParseString(out _);
            }

            if (TryConsume('{'))
            {
                return TrySkipObject();
            }

            if (TryConsume('['))
            {
                return TrySkipArray();
            }

            if (TryConsumeLiteral("true") || TryConsumeLiteral("false") || TryConsumeLiteral("null"))
            {
                return true;
            }

            return TrySkipNumber();
        }

        private bool TrySkipObject()
        {
            SkipWhitespace();
            if (TryConsume('}'))
            {
                return true;
            }

            while (!IsEnd)
            {
                SkipWhitespace();
                if (!TryParseString(out _))
                {
                    AddInvalidJson("Expected property name.");
                    return false;
                }

                SkipWhitespace();
                if (!TryConsume(':'))
                {
                    AddInvalidJson("Expected ':' after property name.");
                    return false;
                }

                if (!TrySkipJsonValue())
                {
                    return false;
                }

                SkipWhitespace();
                if (TryConsume('}'))
                {
                    return true;
                }

                if (!TryConsume(','))
                {
                    AddInvalidJson("Expected ',' or '}' after property value.");
                    return false;
                }
            }

            AddInvalidJson("Unterminated object.");
            return false;
        }

        private bool TrySkipArray()
        {
            SkipWhitespace();
            if (TryConsume(']'))
            {
                return true;
            }

            while (!IsEnd)
            {
                if (!TrySkipJsonValue())
                {
                    return false;
                }

                SkipWhitespace();
                if (TryConsume(']'))
                {
                    return true;
                }

                if (!TryConsume(','))
                {
                    AddInvalidJson("Expected ',' or ']' after array value.");
                    return false;
                }
            }

            AddInvalidJson("Unterminated array.");
            return false;
        }

        private bool TryConsumeLiteral(string literal)
        {
            if (_position + literal.Length > _content.Length)
            {
                return false;
            }

            for (int i = 0; i < literal.Length; i++)
            {
                if (_content[_position + i] != literal[i])
                {
                    return false;
                }
            }

            _position += literal.Length;
            return true;
        }

        private bool TrySkipNumber()
        {
            int start = _position;

            if (!IsEnd && Current == '-')
            {
                _position++;
            }

            if (IsEnd || !char.IsDigit(Current))
            {
                _position = start;
                AddInvalidJson("Expected value.");
                return false;
            }

            if (Current == '0')
            {
                _position++;
            }
            else
            {
                while (!IsEnd && char.IsDigit(Current))
                {
                    _position++;
                }
            }

            if (!IsEnd && Current == '.')
            {
                _position++;
                if (IsEnd || !char.IsDigit(Current))
                {
                    AddInvalidJson("Expected digit after decimal point.");
                    return false;
                }

                while (!IsEnd && char.IsDigit(Current))
                {
                    _position++;
                }
            }

            if (!IsEnd && (Current == 'e' || Current == 'E'))
            {
                _position++;
                if (!IsEnd && (Current == '+' || Current == '-'))
                {
                    _position++;
                }

                if (IsEnd || !char.IsDigit(Current))
                {
                    AddInvalidJson("Expected exponent digit.");
                    return false;
                }

                while (!IsEnd && char.IsDigit(Current))
                {
                    _position++;
                }
            }

            return true;
        }

        private void SkipWhitespace()
        {
            while (!IsEnd && char.IsWhiteSpace(Current))
            {
                _position++;
            }
        }

        private bool TryConsume(char expected)
        {
            if (IsEnd || Current != expected)
            {
                return false;
            }

            _position++;
            return true;
        }

        private void AddInvalidJson(string message)
        {
            _diagnostics.Add(Diagnostic.Create(
                _invalidJsonDescriptor,
                CreateLocation(_path, _text, Math.Min(_position, Math.Max(0, _content.Length - 1))),
                Path.GetFileName(_path),
                message));
        }

        private char Current => _content[_position];

        private bool IsEnd => _position >= _content.Length;

        private static int HexValue(char character)
        {
            if (character >= '0' && character <= '9')
            {
                return character - '0';
            }

            if (character >= 'a' && character <= 'f')
            {
                return character - 'a' + 10;
            }

            if (character >= 'A' && character <= 'F')
            {
                return character - 'A' + 10;
            }

            return -1;
        }
    }

    private static Location CreateLocation(string path, SourceText text, int position)
    {
        int safePosition = Math.Max(0, Math.Min(position, text.Length));
        var span = new TextSpan(safePosition, safePosition < text.Length ? 1 : 0);
        return Location.Create(path, span, text.Lines.GetLinePositionSpan(span));
    }

    private static Diagnostic CreateInvalidJsonDiagnostic(string path, SourceText text, int position, string message) =>
        Diagnostic.Create(
            InvalidJsonDescriptor,
            CreateLocation(path, text, position),
            Path.GetFileName(path),
            message);

    private readonly struct CatalogModel
    {
        public CatalogModel(
            ImmutableArray<string> keys,
            ImmutableArray<ManifestEntry> manifestEntries,
            ImmutableArray<ProviderEntry> providerEntries,
            ImmutableArray<string> cultures,
            ImmutableArray<string> sourceFiles,
            ImmutableArray<Diagnostic> diagnostics)
        {
            Keys = keys;
            ManifestEntries = manifestEntries;
            ProviderEntries = providerEntries;
            Cultures = cultures;
            SourceFiles = sourceFiles;
            Diagnostics = diagnostics;
        }

        public ImmutableArray<string> Keys { get; }

        public ImmutableArray<ManifestEntry> ManifestEntries { get; }

        public ImmutableArray<ProviderEntry> ProviderEntries { get; }

        public ImmutableArray<string> Cultures { get; }

        public ImmutableArray<string> SourceFiles { get; }

        public ImmutableArray<Diagnostic> Diagnostics { get; }
    }

    private readonly struct CatalogFile
    {
        public CatalogFile(string path, ImmutableArray<KeyEntry> keys, ImmutableArray<Diagnostic> diagnostics)
        {
            Path = path;
            Keys = keys;
            Diagnostics = diagnostics;
        }

        public string Path { get; }

        public ImmutableArray<KeyEntry> Keys { get; }

        public ImmutableArray<Diagnostic> Diagnostics { get; }
    }

    private readonly struct KeyEntry
    {
        public KeyEntry(string key, string path, SourceText text, int position, string? value = null, string? culture = null)
        {
            Key = key;
            SourceFile = path;
            Culture = culture ?? InferCulture(path);
            PlaceholderIndexes = value is null ? ImmutableArray<int>.Empty : ExtractPlaceholderIndexes(value);
            Value = value;
            Location = CreateLocation(path, text, position);
        }

        public string Key { get; }

        public string SourceFile { get; }

        public string? Culture { get; }

        public ImmutableArray<int> PlaceholderIndexes { get; }

        public string? Value { get; }

        public Location Location { get; }

        public ManifestEntry ToManifestEntry() => new(Key, Culture, SourceFile, PlaceholderIndexes);
    }

    private readonly struct KeyIdentifier
    {
        public KeyIdentifier(string key, string name)
        {
            Key = key;
            Name = name;
        }

        public string Key { get; }

        public string Name { get; }
    }

    private readonly struct ManifestEntry
    {
        public ManifestEntry(string key, string? culture, string sourceFile, ImmutableArray<int> placeholderIndexes)
        {
            Key = key;
            Culture = culture;
            SourceFile = sourceFile;
            PlaceholderIndexes = placeholderIndexes;
        }

        public string Key { get; }

        public string? Culture { get; }

        public string SourceFile { get; }

        public ImmutableArray<int> PlaceholderIndexes { get; }
    }

    private sealed class GeneratorPoEntry
    {
        public string? Context { get; set; }

        public string MsgId { get; set; } = string.Empty;

        public string MsgIdPlural { get; set; } = string.Empty;

        public string MsgStr { get; set; } = string.Empty;

        public Dictionary<int, string> PluralTranslations { get; } = new Dictionary<int, string>();

        public bool HasContent => Context is not null || MsgId.Length > 0 || MsgStr.Length > 0 || PluralTranslations.Count > 0;
    }

    private readonly struct ProviderEntry
    {
        public ProviderEntry(string key, string? culture, string value)
        {
            Key = key;
            Culture = culture;
            Value = value;
        }

        public string Key { get; }

        public string? Culture { get; }

        public string Value { get; }
    }
}
